name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Docker tag
      id: docker_tag
      run: |
        if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
          echo "TAG=latest" >> $GITHUB_ENV
        else
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: backend
        push: true
        tags: ghcr.io/${{ github.repository_owner }}:${{ env.TAG }}
